spring:
  cloud:
    gateway:
      routes:
        - id : r1
          uri: http://localhost:8081
          predicates:
            - Path=/customers/**
        - id : r2
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**
        - id: r3
          uri: http://localhost:8083
          predicates:
            - Path=/deliveries/**
  application:
    name: gateway-service
server:
  port: 8888